# Generated by Django 3.2.6 on 2021-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0002_song_lyrics'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='musicalbumtosong',
            constraint=models.UniqueConstraint(fields=('musicalbum', 'song'), name='unique_musicalbumtosong'),
        ),
        migrations.AddConstraint(
            model_name='musicalbumtosong',
            constraint=models.UniqueConstraint(fields=('musicalbum', 'disc_number', 'track_number'), name='unique_musicalbumtosong_disc_track'),
        ),
    ]
