# Generated by Django 4.0.5 on 2022-06-27 19:11

import deform.db.models.fields.related
from django.db import migrations
import django.db.models.deletion
import pyamgmt.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0002_booktomotionpicture_unique_booktomotionpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitemmusicalbum',
            name='mediaformat',
            field=deform.db.models.fields.related.ForeignKey(default=pyamgmt.models.models.get_default_mediaformat_audio, on_delete=django.db.models.deletion.SET_DEFAULT, to='pyamgmt.mediaformat'),
        ),
        migrations.AlterField(
            model_name='musicalbum',
            name='mediaformat',
            field=deform.db.models.fields.related.ForeignKey(default=pyamgmt.models.models.get_default_mediaformat_audio, on_delete=django.db.models.deletion.SET_DEFAULT, to='pyamgmt.mediaformat'),
        ),
    ]
