# Generated by Django 3.2.6 on 2021-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0003_auto_20210919_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='accountasset',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='accountassetfinancial',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='accountassetreal',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='accountequity',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='accountexpense',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='accountincome',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='accountliability',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='accountliabilitysecured',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='assetdiscrete',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='assetdiscretecatalogueitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='assetdiscretevehicle',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='assettype',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='catalogueitemdigitalsong',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='catalogueitemmusicalbum',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='catalogueitemtoinvoicelineitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='catalogueitemtoorderlineitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='catalogueitemtopointofsalelineitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitemtononcatalogueitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='mediaformat',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='musicalbum',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='musicalbumartwork',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='musicalbumtomusicartist',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='musicalbumtosong',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='musicartist',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='musicartistactivity',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='musicartisttoperson',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='musicartisttopersonactivity',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='musicartisttosong',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='noncatalogueitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='partycompany',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='partyperson',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='partytype',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='payee',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='pointofsaledocument',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='pointofsalelineitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='pointofsaletotxn',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='txn',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='txnlineitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='vehiclemake',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='vehiclemileage',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='vehicletrim',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
        migrations.AddField(
            model_name='vehicleyear',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this record.', null=True),
        ),
    ]
