# Generated by Django 3.2.6 on 2021-09-19 14:15

import deform.db.models.fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0006_auto_20210919_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notes',
            field=deform.db.models.fields.fields.TextField(blank=True, null=True),
        ),
    ]
