# Generated by Django 3.2.6 on 2021-09-19 16:57

import deform.db.models.fields.fields
from django.db import migrations, models
import pyamgmt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0007_person_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('title', deform.db.models.fields.fields.CharField(max_length=255)),
                ('year_produced', deform.db.models.fields.fields.PositiveSmallIntegerField(blank=True, null=True, validators=[pyamgmt.validators.validate_year_not_future])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
