# Generated by Django 3.2.8 on 2021-10-26 03:50

import deform.db.models.fields.fields
import deform.db.models.fields.related
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0008_motionpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('date_in', deform.db.models.fields.fields.DateField()),
                ('date_out', deform.db.models.fields.fields.DateField(blank=True, null=True)),
                ('mileage_in', deform.db.models.fields.fields.IntegerField()),
                ('mileage_out', deform.db.models.fields.fields.IntegerField()),
                ('vehicle', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyamgmt.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='musicalbum',
            name='musicartists',
            field=deform.db.models.fields.related.ManyToManyField(blank=True, related_name='musicalbums', through='pyamgmt.MusicAlbumToMusicArtist', to='pyamgmt.MusicArtist'),
        ),
        migrations.AlterField(
            model_name='musicalbum',
            name='songs',
            field=deform.db.models.fields.related.ManyToManyField(blank=True, related_name='musicalbums', through='pyamgmt.MusicAlbumToSong', to='pyamgmt.Song'),
        ),
        migrations.CreateModel(
            name='VehicleServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('description', deform.db.models.fields.fields.CharField(max_length=255)),
                ('vehicleservice', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyamgmt.vehicleservice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
