# Generated by Django 3.2.8 on 2021-10-27 05:21

import deform.db.models.fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0010_auto_20211025_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='is_compilation',
            field=deform.db.models.fields.fields.BooleanField(default=False, help_text='Album is a compilation of other songs, such as a Greatest Hits album.'),
        ),
    ]
