# Generated by Django 3.2.8 on 2021-10-27 07:00

import deform.db.models.fields.fields
import deform.db.models.fields.related
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0011_musicalbum_is_compilation'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_instrumental',
            field=deform.db.models.fields.fields.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=deform.db.models.fields.fields.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='MotionPictureToMusicAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', deform.db.models.fields.fields.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', deform.db.models.fields.fields.DateTimeField(auto_now=True)),
                ('motionpicture', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyamgmt.motionpicture')),
                ('musicalbum', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyamgmt.musicalbum')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
