# Generated by Django 3.2.8 on 2021-10-27 07:11

import deform.db.models.fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0012_auto_20211027_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_cover',
            field=deform.db.models.fields.fields.BooleanField(default=False),
        ),
    ]
