# Generated by Django 3.2.8 on 2021-10-27 07:25

import deform.db.models.fields.fields
import deform.db.models.fields.related
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0013_song_is_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongToSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', deform.db.models.fields.fields.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', deform.db.models.fields.fields.DateTimeField(auto_now=True)),
                ('song_derivative', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pyamgmt.song')),
                ('song_original', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pyamgmt.song')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
