# Generated by Django 3.2.8 on 2021-10-28 05:08

import deform.db.models.fields.fields
import deform.db.models.fields.related
from django.db import migrations, models
import django.db.models.deletion
import pyamgmt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0014_songtosong'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicArtistToSongVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', deform.db.models.fields.fields.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', deform.db.models.fields.fields.DateTimeField(auto_now=True)),
                ('musicartist', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyamgmt.musicartist')),
            ],
        ),
        migrations.CreateModel(
            name='SongVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', deform.db.models.fields.fields.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', deform.db.models.fields.fields.DateTimeField(auto_now=True)),
                ('duration', deform.db.models.fields.fields.DurationField(blank=True, null=True, validators=[pyamgmt.validators.validate_positive_timedelta])),
                ('lyrics', deform.db.models.fields.fields.TextField(blank=True, default='')),
                ('version', deform.db.models.fields.fields.CharField(choices=[('ORIGINAL', 'Original'), ('ARRANGEMENT', 'Arrangement'), ('COMPILATION', 'Compilation'), ('COVER', 'Cover'), ('INSTRUMENTAL', 'Instrumental'), ('MASHUP', 'Mash-up'), ('REMASTER', 'Remaster'), ('REMIX', 'Remix')], default='ORIGINAL', max_length=31)),
                ('musicartists', deform.db.models.fields.related.ManyToManyField(related_name='_pyamgmt_songversion_musicartists_+', through='pyamgmt.MusicArtistToSongVersion', to='pyamgmt.MusicArtist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='musicartisttosongversion',
            name='songversion',
            field=deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyamgmt.songversion'),
        ),
        migrations.AddConstraint(
            model_name='musicartisttosongversion',
            constraint=models.UniqueConstraint(fields=('musicartist', 'songversion'), name='unique_musicartisttosongversion'),
        ),
    ]
