# Generated by Django 3.2.8 on 2021-12-26 21:39

from django.db import migrations


def song_to_recording(apps, schema_editor):
    MusicAlbumToSong = apps.get_model('pyamgmt', 'MusicAlbumToSong')  # noqa
    MusicAlbumToSongRecording = apps.get_model('pyamgmt', 'MusicAlbumToSongRecording')  # noqa
    MusicArtistToSong = apps.get_model('pyamgmt', 'MusicArtistToSong')  # noqa
    MusicArtistToSongRecording = apps.get_model('pyamgmt', 'MusicArtistToSongRecording')  # noqa
    Song = apps.get_model('pyamgmt', 'Song')  # noqa
    SongRecording = apps.get_model('pyamgmt', 'SongRecording')  # noqa
    qs_song = (
        Song.objects
        .prefetch_related(
            'musicalbumtosong_set',
            'musicartisttosong_set'
        )
    )
    # Copy over duration, lyrics
    for song in qs_song:
        song_recording = SongRecording(
            duration=song.duration,
            lyrics=song.lyrics,
            song=song
        )
        song_recording.save()
        # Copy M2M fields to new intermediate tables
        for m2m in song.musicalbumtosong_set.all():
            musicalbumtosongrecording = MusicAlbumToSongRecording(
                disc_number=m2m.disc_number,
                musicalbum=m2m.musicalbum,
                songrecording=song_recording,
                track_number=m2m.track_number
            )
            musicalbumtosongrecording.save()
        for m2m in song.musicartisttosong_set.all():
            musicartisttosongrecording = MusicArtistToSongRecording(
                musicartist=m2m.musicartist,
                songrecording=song_recording
            )
            musicartisttosongrecording.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0016_auto_20211226_1638'),
    ]

    operations = [
        migrations.RunPython(song_to_recording, reverse_code=migrations.RunPython.noop, elidable=True)
    ]
