# Generated by Django 3.2.8 on 2021-12-26 22:01

import deform.db.models.fields.related
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0017_auto_20211226_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='songrecordings',
            field=deform.db.models.fields.related.ManyToManyField(blank=True, through='pyamgmt.MusicAlbumToSongRecording', to='pyamgmt.SongRecording'),
        ),
    ]
