# Generated by Django 3.2.8 on 2021-12-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0018_musicalbum_songrecordings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalbum',
            name='songs',
        ),
        migrations.DeleteModel(
            name='MusicAlbumToSong',
        ),
    ]
