# Generated by Django 3.2.8 on 2021-12-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0019_auto_20211226_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_cover',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_instrumental',
        ),
    ]
