# Generated by Django 4.0 on 2021-12-28 02:36

import deform.db.models.fields.fields
import deform.db.models.fields.related
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0020_auto_20211226_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='songtosong',
            name='song_relationship',
            field=deform.db.models.fields.fields.CharField(choices=[('ARRANGEMENT', 'Arrangement'), ('COVER', 'Cover'), ('INSTRUMENTAL', 'Instrumental'), ('OVERTURE', 'Overture'), ('MASHUP', 'Mash-up'), ('REMIX', 'Remix')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicartist',
            name='songs',
            field=deform.db.models.fields.related.ManyToManyField(blank=True, related_name='+', through='pyamgmt.MusicArtistToSong', to='pyamgmt.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='musicartists',
            field=deform.db.models.fields.related.ManyToManyField(related_name='+', through='pyamgmt.MusicArtistToSong', to='pyamgmt.MusicArtist'),
        ),
        migrations.AlterField(
            model_name='songrecording',
            name='musicartists',
            field=deform.db.models.fields.related.ManyToManyField(related_name='+', through='pyamgmt.MusicArtistToSongRecording', to='pyamgmt.MusicArtist'),
        ),
        migrations.AddConstraint(
            model_name='songtosong',
            constraint=models.UniqueConstraint(fields=('song_derivative', 'song_original'), name='unique_songtosong'),
        ),
    ]
