# Generated by Django 4.0 on 2021-12-28 06:57

import deform.db.models.fields.fields
import deform.db.models.fields.related
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0021_songtosong_song_relationship_alter_musicartist_songs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', deform.db.models.fields.fields.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', deform.db.models.fields.fields.DateTimeField(auto_now=True)),
                ('title', deform.db.models.fields.fields.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotionPictureRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', deform.db.models.fields.fields.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', deform.db.models.fields.fields.DateTimeField(auto_now=True)),
                ('motionpicture', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyamgmt.motionpicture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookToMotionPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', deform.db.models.fields.fields.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', deform.db.models.fields.fields.DateTimeField(auto_now=True)),
                ('book', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyamgmt.book')),
                ('motionpicture', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyamgmt.motionpicture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
