# Generated by Django 4.0 on 2021-12-28 16:53

import deform.db.models.fields.fields
import deform.db.models.fields.related
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0022_book_motionpicturerecording_booktomotionpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', deform.db.models.fields.fields.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', deform.db.models.fields.fields.DateTimeField(auto_now=True)),
                ('edition', deform.db.models.fields.fields.PositiveSmallIntegerField()),
                ('book', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyamgmt.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', deform.db.models.fields.fields.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', deform.db.models.fields.fields.DateTimeField(auto_now=True)),
                ('bookedition', deform.db.models.fields.related.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyamgmt.bookedition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='bookedition',
            constraint=models.UniqueConstraint(fields=('book', 'edition'), name='unique_bookedition'),
        ),
    ]
