# Generated by Django 4.0 on 2021-12-28 16:56

import deform.db.models.fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0023_bookedition_bookpublication_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogueItem',
            new_name='CatalogItem',
        ),
        migrations.AlterField(
            model_name='assetdiscrete',
            name='subtype',
            field=deform.db.models.fields.fields.CharField(choices=[('CATALOG_ITEM', 'CATALOG_ITEM'), ('VEHICLE', 'VEHICLE')], default='NONE', max_length=31),
        ),
    ]
