# Generated by Django 4.0 on 2021-12-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0024_rename_catalogueitem_catalogitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetDiscreteCatalogueItem',
            new_name='AssetDiscreteCatalogItem',
        ),
        migrations.RenameModel(
            old_name='CatalogueItemDigitalSong',
            new_name='CatalogItemDigitalSong',
        ),
        migrations.RenameModel(
            old_name='CatalogueItemMusicAlbum',
            new_name='CatalogItemMusicAlbum',
        ),
        migrations.RenameModel(
            old_name='CatalogueItemToInvoiceLineItem',
            new_name='CatalogItemToInvoiceLineItem',
        ),
        migrations.RenameModel(
            old_name='CatalogueItemToOrderLineItem',
            new_name='CatalogItemToOrderLineItem',
        ),
        migrations.RenameModel(
            old_name='CatalogueItemToPointOfSaleLineItem',
            new_name='CatalogItemToPointOfSaleLineItem',
        ),
    ]
