# Generated by Django 4.0 on 2021-12-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0025_rename_assetdiscretecatalogueitem_assetdiscretecatalogitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NonCatalogueItem',
            new_name='NonCatalogItem',
        ),
    ]
