# Generated by Django 4.0 on 2021-12-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0026_rename_noncatalogueitem_noncatalogitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceLineItemToNonCatalogueItem',
            new_name='InvoiceLineItemToNonCatalogItem',
        ),
    ]
