# Generated by Django 4.0 on 2022-01-04 09:40

import deform.db.models.fields.fields
import django.core.validators
from django.db import migrations
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0028_rename_catalogueitem_assetdiscretecatalogitem_catalogitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='isbn',
            field=deform.db.models.fields.fields.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(code='invalid', message='ISBN may only contain digits and "X".', regex=re.compile('^[0-9xX]+\\Z'))]),
        ),
    ]
