# Generated by Django 4.0 on 2022-01-04 10:47

import deform.db.models.fields.fields
import django.core.validators
from django.db import migrations
import pyamgmt.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0029_alter_catalogitem_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='isbn_13',
            field=deform.db.models.fields.fields.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator(code='invalid', message='Enter a valid digit.', regex=re.compile('^\\d+\\Z')), pyamgmt.validators.validate_isbn_13_check_digit]),
        ),
    ]
