# Generated by Django 4.0 on 2022-01-04 11:46

import deform.db.models.fields.fields
import django.core.validators
from django.db import migrations
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0031_rename_upc_catalogitem_upc_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='ean_13',
            field=deform.db.models.fields.fields.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator(code='invalid', message='Enter a valid digit.', regex=re.compile('^\\d+\\Z'))]),
        ),
    ]
