# Generated by Django 4.0.4 on 2022-05-27 09:13

import deform.db.models.fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyamgmt', '0032_catalogitem_ean_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=deform.db.models.fields.fields.CharField(max_length=255, unique=True),
        ),
    ]
