# Generated by Django 5.0 on 2024-01-10 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0031_delete_beerxuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXBeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('has_tried', models.BooleanField(blank=True, null=True)),
                ('worthy', models.BooleanField(blank=True, null=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_x_beer_set', related_query_name='user_x_beer', to='core.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_x_beer_set', related_query_name='user_x_beer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User <-> Beer',
                'verbose_name_plural': 'User <-> Beer',
            },
        ),
        migrations.AddConstraint(
            model_name='userxbeer',
            constraint=models.UniqueConstraint(fields=('user', 'beer'), name='unique_user_x_beer'),
        ),
    ]
