# Generated by Django 4.1.7 on 2023-03-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_partyperson_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountasset',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_asset', serialize=False, to='core.account'),
        ),
        migrations.AlterField(
            model_name='accountassetfinancial',
            name='account_asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_asset_financial', serialize=False, to='core.accountasset'),
        ),
        migrations.AlterField(
            model_name='accountassetreal',
            name='account_asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_asset_real', serialize=False, to='core.accountasset'),
        ),
        migrations.AlterField(
            model_name='accountequity',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_equity', serialize=False, to='core.account'),
        ),
        migrations.AlterField(
            model_name='accountexpense',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_expense', serialize=False, to='core.account'),
        ),
        migrations.AlterField(
            model_name='accountincome',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_income', serialize=False, to='core.account'),
        ),
        migrations.AlterField(
            model_name='accountliability',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_liability', serialize=False, to='core.account'),
        ),
        migrations.AlterField(
            model_name='accountliabilitysecured',
            name='account_liability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_liability_secured', serialize=False, to='core.accountliability'),
        ),
        migrations.AlterField(
            model_name='assetdiscrete',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asset_discrete', serialize=False, to='core.asset'),
        ),
        migrations.AlterField(
            model_name='assetdiscretecatalogitem',
            name='asset_discrete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asset_discrete_catalog_item', serialize=False, to='core.assetdiscrete'),
        ),
        migrations.AlterField(
            model_name='assetdiscretevehicle',
            name='asset_discrete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asset_discrete_vehicle', serialize=False, to='core.assetdiscrete'),
        ),
        migrations.AlterField(
            model_name='assetdiscretevehicle',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asset_discrete_vehicle', to='core.vehicle'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asset_inventory', serialize=False, to='core.asset'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='catalog_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asset_inventory', to='core.catalogitem'),
        ),
        migrations.AlterField(
            model_name='catalogitemdigitalsong',
            name='catalog_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_item_digital_song', serialize=False, to='core.catalogitem'),
        ),
        migrations.AlterField(
            model_name='catalogitemmusicalbumproduction',
            name='catalog_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_item_music_album_production', serialize=False, to='core.catalogitem'),
        ),
        migrations.AlterField(
            model_name='catalogitemtoinvoicelineitem',
            name='invoice_line_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_item_to_invoice_line_item', serialize=False, to='core.invoicelineitem'),
        ),
        migrations.AlterField(
            model_name='catalogitemtoorderlineitem',
            name='orderlineitem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_item_to_order_line_item', serialize=False, to='core.orderlineitem'),
        ),
        migrations.AlterField(
            model_name='catalogitemtopointofsalelineitem',
            name='point_of_sale_line_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_item_to_point_of_sale_line_item', serialize=False, to='core.pointofsalelineitem'),
        ),
        migrations.AlterField(
            model_name='invoicelineitemtononcatalogitem',
            name='invoice_line_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='invoice_line_item_to_non_catalog_item', serialize=False, to='core.invoicelineitem'),
        ),
        migrations.AlterField(
            model_name='partybusiness',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='party_business', serialize=False, to='core.party'),
        ),
        migrations.AlterField(
            model_name='partyperson',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='party_person', serialize=False, to='core.party'),
        ),
        migrations.AlterField(
            model_name='partyperson',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_person', to='core.person'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='txn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_of_sale', to='core.txn'),
        ),
        migrations.AlterField(
            model_name='pointofsaletotxn',
            name='point_of_sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_of_sale_to_txn', to='core.pointofsale'),
        ),
        migrations.AlterField(
            model_name='pointofsaletotxn',
            name='txn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_of_sale_to_txn', to='core.txn'),
        ),
    ]
