# Generated by Django 4.0.5 on 2022-08-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTableBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiTableSubclass',
            fields=[
                ('multitablebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox.multitablebase')),
                ('subclass_name', models.CharField(max_length=31)),
            ],
            bases=('sandbox.multitablebase',),
        ),
        migrations.AddConstraint(
            model_name='multitablesubclass',
            constraint=models.UniqueConstraint(fields=('multitablebase_ptr', 'subclass_name'), name='uix_multitablesubclass'),
        ),
    ]
