# Generated by Django 4.0.5 on 2022-08-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOneTableBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneToOneTableSubclass',
            fields=[
                ('onetoonetablebase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sandbox.onetoonetablebase')),
                ('subclass_name', models.CharField(max_length=31)),
            ],
        ),
        migrations.AddConstraint(
            model_name='onetoonetablesubclass',
            constraint=models.UniqueConstraint(fields=('onetoonetablebase', 'subclass_name'), name='uix_onetoonetablesubclass'),
        ),
    ]
