# Generated by Django 4.0.5 on 2022-08-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0003_onetooneparentlinkbase_onetooneparentlinksubclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTableWithPtrBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiTableWithPtrSubclass',
            fields=[
                ('superclass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sandbox.multitablewithptrbase')),
                ('subclass_name', models.CharField(max_length=31)),
            ],
            bases=('sandbox.multitablewithptrbase',),
        ),
        migrations.AddConstraint(
            model_name='multitablewithptrsubclass',
            constraint=models.UniqueConstraint(fields=('superclass', 'subclass_name'), name='uix_multitablewithptrsubclass'),
        ),
    ]
