# Generated by Django 4.1.7 on 2023-03-23 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralModelWithFK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_model_with_fk_set', related_query_name='general_model_with_fk', to='sandbox.generaltestmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
