# Generated by Django 5.0 on 2023-12-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0002_asymmetricaltestmodel_symmetricaltestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asymmetricaltestmodel',
            name='m2m',
            field=models.ManyToManyField(blank=True, to='sandbox.asymmetricaltestmodel'),
        ),
        migrations.AlterField(
            model_name='symmetricaltestmodel',
            name='m2m',
            field=models.ManyToManyField(blank=True, to='sandbox.symmetricaltestmodel'),
        ),
    ]
