# Generated by Django 5.0 on 2023-12-22 19:05

import django_base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django_base.validators.validate_date_not_future]),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, validators=[django_base.validators.validate_date_not_future]),
        ),
    ]
