# Generated by Django 5.0 on 2023-12-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personxpersonrelation',
            name='relation',
            field=models.CharField(choices=[('BROTHER', 'Brother'), ('CHILD', 'Child'), ('DAUGHTER', 'Daughter'), ('FATHER', 'Father'), ('GRANDCHILD', 'Grandchild'), ('GRANDDAUGHTER', 'Granddaughter'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('GRANDPARENT', 'Grandparent'), ('GRANDSON', 'Grandson'), ('MOTHER', 'Mother'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('SISTER', 'Sister'), ('SON', 'Son')], help_text="Relation FROM Person A TO Person B. Person A is Person B's ...", max_length=13),
        ),
    ]
