# Generated by Django 5.0 on 2023-12-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personxpersonrelation',
            name='relation',
            field=models.CharField(choices=[('CHILD', 'Child'), ('GRANDCHILD', 'Grandchild'), ('GRANDPARENT', 'Grandparent'), ('MOTHER', 'Mother'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling')], help_text="Relation FROM Person A TO Person B. Person A is Person B's ...", max_length=13),
        ),
    ]
