# Generated by Django 5.0 on 2023-12-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_personxpersonrelation_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personxpersonrelationship',
            name='relationship',
            field=models.CharField(blank=True, choices=[('CLASSMATE', 'Classmate'), ('FRIEND', 'Friend'), ('HUSBAND', 'Husband'), ('INSTRUCTOR', 'Instructor'), ('PARTNER', 'Partner'), ('SCHOOLMATE', 'Schoolmate'), ('SPOUSE', 'Spouse'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('WIFE', 'Wife')], help_text="The relationship FROM person A TO person B. Person A is Person B's ...", max_length=10),
        ),
    ]
