# Generated by Django 5.0 on 2023-12-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicartist',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicArtistXPerson', to='core.person'),
        ),
    ]
