# Generated by Django 5.0 on 2023-12-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_videogameplatform_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountasset',
            options={'verbose_name_plural': 'Account::Asset'},
        ),
        migrations.AlterModelOptions(
            name='accountassetfinancial',
            options={'verbose_name_plural': 'Account::Asset::Financial'},
        ),
        migrations.AlterModelOptions(
            name='accountassetreal',
            options={'verbose_name_plural': 'Account::Asset::Real'},
        ),
        migrations.AlterModelOptions(
            name='accountequity',
            options={'verbose_name_plural': 'Account::Equity'},
        ),
        migrations.AlterModelOptions(
            name='accountexpense',
            options={'verbose_name_plural': 'Account::Expense'},
        ),
        migrations.AlterModelOptions(
            name='accountincome',
            options={'verbose_name_plural': 'Account::Income'},
        ),
        migrations.AlterModelOptions(
            name='accountliability',
            options={'verbose_name_plural': 'Account::Liability'},
        ),
        migrations.AlterModelOptions(
            name='accountliabilitysecured',
            options={'verbose_name_plural': 'Account::Liability::Secured'},
        ),
        migrations.AlterModelOptions(
            name='assetdiscrete',
            options={'verbose_name': 'Asset::Discrete', 'verbose_name_plural': 'Asset::Discrete'},
        ),
        migrations.AlterModelOptions(
            name='assetdiscretecatalogitem',
            options={'verbose_name': 'Asset::Discrete::CatalogItem', 'verbose_name_plural': 'Asset::Discrete::CatalogItem'},
        ),
        migrations.AlterModelOptions(
            name='assetdiscretevehicle',
            options={'verbose_name': 'Asset::Discrete::Vehicle', 'verbose_name_plural': 'Asset::Discrete::Vehicle'},
        ),
        migrations.AlterModelOptions(
            name='assetinventory',
            options={'verbose_name': 'Asset::Inventory', 'verbose_name_plural': 'Asset::Inventory'},
        ),
        migrations.AlterModelOptions(
            name='musicalbumartwork',
            options={'verbose_name_plural': 'music album artwork'},
        ),
        migrations.AlterModelOptions(
            name='videogameseries',
            options={'verbose_name_plural': 'video game series'},
        ),
    ]
