# Generated by Django 5.0 on 2023-12-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_accountasset_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='party',
            name='subtype',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('PERSON', 'Person')], max_length=31),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer', to='core.business'),
        ),
        migrations.AddField(
            model_name='partybusiness',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_business', to='core.business'),
        ),
        migrations.CreateModel(
            name='CatalogItemXVideoGameEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item_x_video_game_edition_set', related_query_name='catalog_item_x_video_game_edition', to='core.catalogitem')),
                ('video_game_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item_x_video_game_edition_set', related_query_name='catalog_item_x_video_game_edition', to='core.videogameedition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
