# Generated by Django 5.0 on 2023-12-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_musicartist_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicartist',
            name='disambiguator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='musicartist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='musicartist',
            constraint=models.UniqueConstraint(fields=('name', 'disambiguator'), name='unique_music_artist'),
        ),
    ]
