# Generated by Django 5.0 on 2023-12-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personxpersonrelationship',
            name='relationship',
            field=models.CharField(blank=True, choices=[('CLASSMATE', 'Classmate'), ('FRIEND', 'Friend'), ('INSTRUCTOR', 'Instructor'), ('PARTNER', 'Partner'), ('SCHOOLMATE', 'Schoolmate'), ('SPOUSE', 'Spouse'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], help_text="The relationship FROM person A TO person B. Person A is Person B's ...", max_length=10),
        ),
    ]
