# Generated by Django 5.0 on 2023-12-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_personxpersonrelationship_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbumedition',
            name='song_recordings',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicAlbumEditionXSongRecording', to='core.songrecording'),
        ),
    ]
