# Generated by Django 5.0 on 2024-01-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_personxpersonrelationship_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionpicturexperson',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
