# Generated by Django 5.0 on 2023-12-30 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_musicalbumedition_song_recordings'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='cover_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.musicalbumartwork'),
        ),
        migrations.AlterField(
            model_name='musicalbum',
            name='music_artists',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicAlbumXMusicArtist', to='core.musicartist'),
        ),
    ]
