# Generated by Django 5.0 on 2023-12-24 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_musicartist_disambiguator_alter_musicartist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRoleXPersonXSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('music_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_role_x_person_x_song_set', related_query_name='music_role_x_person_x_song', to='core.musicrole')),
                ('person_x_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_role_x_person_x_song_set', related_query_name='music_role_x_person_x_song', to='core.personxsong')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
