# Generated by Django 5.0 on 2023-12-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_business_alter_party_subtype_manufacturer_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogameseries',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
