# Generated by Django 5.0 on 2023-12-24 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_musicrolexpersonxsong'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbumXPersonXMusicRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('music_album_x_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_x_person_x_music_role_set', related_query_name='music_album_x_person_x_music_role', to='core.musicalbumxperson')),
                ('music_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_x_person_x_music_role_set', related_query_name='music_album_x_person_x_music_role', to='core.musicrole')),
            ],
        ),
        migrations.DeleteModel(
            name='MusicAlbumXPersonRole',
        ),
        migrations.AddConstraint(
            model_name='musicalbumxpersonxmusicrole',
            constraint=models.UniqueConstraint(fields=('music_role', 'music_album_x_person'), name='unique_music_album_x_person_role'),
        ),
    ]
