# Generated by Django 5.0 on 2023-12-15 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_videogameseries_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGamePlatformRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(blank=True, choices=[('AU', 'Australia'), ('EU', 'Europe'), ('JP', 'Japan'), ('NA', 'North America')], default='', max_length=2)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('video_game_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_game_platform_region_set', related_query_name='video_game_platform_region', to='core.videogameplatform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
