# Generated by Django 5.0 on 2024-01-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_motionpicturexperson_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.PersonXPhoto', to='core.person'),
        ),
    ]
