# Generated by Django 5.0 on 2023-12-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_musicalbumxpersonxmusicrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='musical_instruments',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicalInstrumentXPerson', to='core.musicalinstrument'),
        ),
    ]
