# Generated by Django 5.0 on 2023-12-16 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_videogameplatformregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountassetreal',
            name='asset',
        ),
        migrations.AddField(
            model_name='assetdiscrete',
            name='account_asset_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_discrete_set', related_query_name='asset_discrete', to='core.accountassetreal'),
        ),
    ]
