# Generated by Django 5.0 on 2023-12-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_person_musical_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionpicture',
            name='music_albums',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MotionPictureXMusicAlbum', to='core.musicalbum'),
        ),
    ]
