# Generated by Django 5.0 on 2024-01-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_videogamedeveloper_videogame_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogame',
            name='developer',
        ),
    ]
