# Generated by Django 5.0 on 2023-12-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_accountassetreal_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdiscrete',
            name='account_asset_real',
        ),
    ]
