# Generated by Django 5.0 on 2023-12-24 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_motionpicture_music_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitemdigitalsong',
            name='song_recording',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item_digital_song', to='core.songrecording'),
        ),
    ]
