# Generated by Django 5.0 on 2023-12-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_assetdiscrete_account_asset_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='account_asset_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_set', related_query_name='asset', to='core.accountassetreal'),
        ),
    ]
