# Generated by Django 5.0 on 2024-01-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_videogame_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionpicture',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
