# Generated by Django 5.0 on 2024-01-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_motionpicture_notes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assetdiscretexcatalogitem',
            constraint=models.UniqueConstraint(fields=('asset_discrete', 'catalog_item'), name='unique_asset_discrete_x_catalog_item'),
        ),
    ]
