# Generated by Django 5.0 on 2024-01-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assetdiscretexcatalogitem_unique_asset_discrete_x_catalog_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetDiscreteXCatalogItem',
        ),
    ]
