# Generated by Django 5.0 on 2023-12-16 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_catalogitemmusicalbumproduction_media_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonCatalogItemXOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('non_catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_catalog_item_x_order_line_item_set', related_query_name='non_catalog_item_x_order_line_item', to='core.noncatalogitem')),
                ('order_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_catalog_item_x_order_line_item_set', related_query_name='non_catalog_item_x_order_line_item', to='core.orderlineitem')),
            ],
        ),
        migrations.CreateModel(
            name='NonCatalogItemXPointOfSaleLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('non_catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_catalog_item_x_point_of_sale_line_item_set', related_query_name='non_catalog_item_x_point_of_sale_line_item', to='core.noncatalogitem')),
                ('point_of_sale_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_catalog_item_x_point_of_sale_line_item_set', related_query_name='non_catalog_item_x_point_of_sale_line_item', to='core.pointofsalelineitem')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGamePlatformEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=31)),
                ('video_game_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_game_platform_edition_set', related_query_name='video_game_platform_edition', to='core.videogameplatform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CatalogItemXVideoGamePlatform',
        ),
        migrations.AddConstraint(
            model_name='noncatalogitemxorderlineitem',
            constraint=models.UniqueConstraint(fields=('non_catalog_item', 'order_line_item'), name='unique_non_catalog_item_x_order_line_item'),
        ),
        migrations.AddConstraint(
            model_name='noncatalogitemxpointofsalelineitem',
            constraint=models.UniqueConstraint(fields=('non_catalog_item', 'point_of_sale_line_item'), name='unique_non_catalog_item_x_point_of_sale_line_item'),
        ),
    ]
