# Generated by Django 5.0 on 2023-12-16 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_noncatalogitemxorderlineitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItemXVideoGamePlatformEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item_x_video_game_platform_edition_set', related_query_name='catalog_item_x_video_game_platform_edition', to='core.catalogitem')),
                ('video_game_platform_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item_x_video_game_platform_edition_set', related_query_name='catalog_item_x_video_game_platform_edition', to='core.videogameplatformedition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='catalogitemxvideogameplatformedition',
            constraint=models.UniqueConstraint(fields=('catalog_item', 'video_game_platform_edition'), name='unique_catalog_item_x_video_game_platform_edition'),
        ),
    ]
