# Generated by Django 5.0 on 2024-01-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_assetdiscrete_subtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountassetreal',
            options={'verbose_name': 'Account::Asset::Real', 'verbose_name_plural': 'Account::Asset::Real'},
        ),
        migrations.AlterModelOptions(
            name='accountequity',
            options={'verbose_name': 'Account::Equity', 'verbose_name_plural': 'Account::Equity'},
        ),
        migrations.AlterModelOptions(
            name='accountexpense',
            options={'verbose_name': 'Account::Expense', 'verbose_name_plural': 'Account::Expense'},
        ),
        migrations.AlterModelOptions(
            name='accountincome',
            options={'verbose_name': 'Account::Income', 'verbose_name_plural': 'Account::Income'},
        ),
        migrations.AlterModelOptions(
            name='accountliability',
            options={'verbose_name': 'Account::Liability', 'verbose_name_plural': 'Account::Liability'},
        ),
        migrations.AlterModelOptions(
            name='accountliabilitysecured',
            options={'verbose_name': 'Account::Liability::Secured', 'verbose_name_plural': 'Account::Liability::Secured'},
        ),
        migrations.AlterModelOptions(
            name='assetdiscretexcatalogitem',
            options={'verbose_name': 'Asset::Discrete <-> CatalogItem', 'verbose_name_plural': 'Asset::Discrete <-> CatalogItem'},
        ),
        migrations.RenameField(
            model_name='musicalbumxperson',
            old_name='comments',
            new_name='notes',
        ),
    ]
