# Generated by Django 5.0 on 2023-12-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_songarrangement_music_artists_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='songarrangement',
            name='unique_song_arrangement',
        ),
        migrations.AddField(
            model_name='song',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.PersonXSong', to='core.person'),
        ),
        migrations.AlterField(
            model_name='song',
            name='arrangements',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.SongXSongArrangement', to='core.songarrangement'),
        ),
        migrations.AlterField(
            model_name='song',
            name='music_artists',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicArtistXSong', to='core.musicartist'),
        ),
        migrations.AddConstraint(
            model_name='songarrangement',
            constraint=models.UniqueConstraint(fields=('title', 'disambiguator', 'description'), name='unique_song_arrangement', nulls_distinct=True),
        ),
    ]
