# Generated by Django 5.0 on 2024-01-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_accountassetreal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookxmotionpicture',
            options={'verbose_name': 'Book <-> MotionPicture', 'verbose_name_plural': 'Book <-> MotionPicture'},
        ),
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'verbose_name': 'CatalogItem', 'verbose_name_plural': 'CatalogItem'},
        ),
        migrations.AlterModelOptions(
            name='catalogitemmotionpicturerecording',
            options={'verbose_name': 'CatalogItem <-> MotionPictureRecording', 'verbose_name_plural': 'CatalogItem <-> MotionPictureRecording'},
        ),
        migrations.AlterModelOptions(
            name='musicalbumxperson',
            options={'verbose_name': 'MusicAlbum <-> Person', 'verbose_name_plural': 'MusicAlbum <-> Person'},
        ),
        migrations.AlterModelOptions(
            name='musicalbumxpersonxmusicrole',
            options={'verbose_name': 'MusicAlbum <-> Person <-> MusicRole', 'verbose_name_plural': 'MusicAlbum <-> Person <-> MusicRole'},
        ),
        migrations.AlterModelOptions(
            name='musicalbumxvideogame',
            options={'verbose_name': 'MusicAlbum <-> VideoGame', 'verbose_name_plural': 'MusicAlbum <-> VideoGame'},
        ),
        migrations.AlterModelOptions(
            name='musicalinstrumentxperson',
            options={'verbose_name': 'MusicalInstrument <-> Person', 'verbose_name_plural': 'MusicalInstrument <-> Person'},
        ),
        migrations.AlterModelOptions(
            name='musicartistxmusictag',
            options={'verbose_name': 'MusicArtist <-> MusicTag', 'verbose_name_plural': 'MusicArtist <-> MusicTag'},
        ),
        migrations.AlterModelOptions(
            name='musicartistxperson',
            options={'verbose_name': 'MusicArtist <-> Person', 'verbose_name_plural': 'MusicArtist <-> Person'},
        ),
        migrations.AlterModelOptions(
            name='musicartistxpersonactivity',
            options={'verbose_name': 'MusicArtist <-> Person Activity', 'verbose_name_plural': 'MusicArtist <-> Person Activity'},
        ),
        migrations.AlterModelOptions(
            name='musicartistxsong',
            options={'verbose_name': 'MusicArtist <-> Song', 'verbose_name_plural': 'MusicArtist <-> Song'},
        ),
        migrations.AlterModelOptions(
            name='musicartistxsongarrangement',
            options={'verbose_name': 'MusicArtist <-> SongArrangement', 'verbose_name_plural': 'MusicArtist <-> SongArrangement'},
        ),
        migrations.AlterModelOptions(
            name='musicartistxsongperformance',
            options={'verbose_name': 'MusicArtist <-> SongPerformance', 'verbose_name_plural': 'MusicArtist <-> SongPerformance'},
        ),
        migrations.AddConstraint(
            model_name='musicartistxpersonactivity',
            constraint=models.UniqueConstraint(fields=('music_artist_x_person', 'year_active'), name='unique_music_artist_x_person_activity_year_active'),
        ),
    ]
