# Generated by Django 5.0 on 2023-12-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_motionpicture_songs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicartist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicArtistXMusicTag', to='core.musictag'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='music_albums',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicAlbumXVideoGame', to='core.musicalbum'),
        ),
    ]
