# Generated by Django 5.0 on 2024-01-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_bookxmotionpicture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Account'},
        ),
        migrations.AlterModelOptions(
            name='accountasset',
            options={'verbose_name': 'Account::Asset', 'verbose_name_plural': 'Account::Asset'},
        ),
        migrations.AlterModelOptions(
            name='accountassetfinancial',
            options={'verbose_name': 'Account::Asset::Financial', 'verbose_name_plural': 'Account::Asset::Financial'},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Asset'},
        ),
        migrations.AlterModelOptions(
            name='beer',
            options={'verbose_name_plural': 'breweries'},
        ),
        migrations.AlterModelOptions(
            name='motionpicturexmusicalbum',
            options={'verbose_name': 'MotionPicture <-> MusicAlbum', 'verbose_name_plural': 'MotionPicture <-> MusicAlbum'},
        ),
        migrations.AlterModelOptions(
            name='motionpicturexperson',
            options={'verbose_name': 'MotionPicture <-> Person', 'verbose_name_plural': 'MotionPicture <-> Person'},
        ),
        migrations.AlterModelOptions(
            name='motionpicturexsong',
            options={'verbose_name': 'MotionPicture <-> Song', 'verbose_name_plural': 'MotionPicture <-> Song'},
        ),
        migrations.AlterModelOptions(
            name='musicalbumxmusicartist',
            options={'verbose_name': 'MusicAlbum <-> MusicArtist', 'verbose_name_plural': 'MusicAlbum <-> MusicArtist'},
        ),
        migrations.AlterModelOptions(
            name='musicalbumxmusictag',
            options={'verbose_name': 'MusicAlbum <-> MusicTag', 'verbose_name_plural': 'MusicAlbum <-> MusicTag'},
        ),
    ]
