# Generated by Django 5.0 on 2023-12-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_person_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='subtype_acquaintance',
        ),
        migrations.RemoveField(
            model_name='person',
            name='subtype_notable',
        ),
    ]
