# Generated by Django 5.0 on 2023-12-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_person_subtype_acquaintance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicartistxpersonactivity',
            old_name='music_artist_to_person',
            new_name='music_artist_x_person',
        ),
    ]
