# Generated by Django 5.0 on 2023-12-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_musicartist_tags_videogame_music_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='songarrangement',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.PersonXSongArrangement', to='core.person'),
        ),
    ]
