# Generated by Django 5.0 on 2023-12-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_music_artist_to_person_musicartistxpersonactivity_music_artist_x_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicartist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicAlbumXMusicArtist', to='core.musicalbum'),
        ),
    ]
