# Generated by Django 5.0 on 2024-01-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_personxphoto_options_alter_personxsong_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogame',
            old_name='year_published',
            new_name='year_first_published',
        ),
    ]
