# Generated by Django 5.0 on 2023-12-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_songarrangement_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicartist',
            old_name='people',
            new_name='personnel',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='people',
            new_name='personnel',
        ),
        migrations.RenameField(
            model_name='songarrangement',
            old_name='people',
            new_name='personnel',
        ),
    ]
