# Generated by Django 5.0 on 2024-01-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_year_published_videogame_year_first_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='attribution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='year_taken',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
