# Generated by Django 5.0 on 2023-12-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_musicartist_albums'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicAlbumXSongRecording',
        ),
    ]
