# Generated by Django 5.0 on 2023-12-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_people_musicartist_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, help_text='Title or Salutation', max_length=31),
        ),
    ]
