# Generated by Django 5.0 on 2024-01-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_photo_attribution_photo_year_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='attribution',
            field=models.TextField(blank=True),
        ),
    ]
