# Generated by Django 5.0 on 2023-12-16 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_musicalbumxsongrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbumedition',
            name='name',
            field=models.CharField(default='', max_length=31),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MusicAlbumEditionXSongRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('disc_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('track_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('music_album_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_edition_x_song_recording_set', related_query_name='music_album_edition_x_song_recording', to='core.musicalbumedition')),
                ('song_recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_edition_x_song_recording_set', related_query_name='music_album_edition_x_song_recording', to='core.songrecording')),
            ],
        ),
        migrations.AddConstraint(
            model_name='musicalbumeditionxsongrecording',
            constraint=models.UniqueConstraint(fields=('music_album_edition', 'song_recording'), name='unique_music_album_edition_x_song_recording'),
        ),
        migrations.AddConstraint(
            model_name='musicalbumeditionxsongrecording',
            constraint=models.UniqueConstraint(fields=('music_album_edition', 'disc_number', 'track_number'), name='unique_music_album_edition_x_song_recording_disc_track'),
        ),
    ]
