# Generated by Django 5.0 on 2023-12-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_person_music_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbumedition',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
