# Generated by Django 5.0 on 2023-12-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_musicalbumedition_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='musicalbumeditionxsongrecording',
            name='unique_music_album_edition_x_song_recording_disc_track',
        ),
        migrations.AlterField(
            model_name='musicalbumedition',
            name='name',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AddConstraint(
            model_name='musicalbumeditionxsongrecording',
            constraint=models.UniqueConstraint(fields=('music_album_edition', 'disc_number', 'track_number'), name='unique_music_album_edition_x_song_recording_disc_track'),
        ),
    ]
