# Generated by Django 5.0 on 2023-12-27 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_musicalbumedition_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonXPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(blank=True, help_text='The relationship FROM person A TO person B', max_length=255)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonXPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_x_photo_set', related_query_name='person_x_photo', to='core.person')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_x_photo_set', related_query_name='person_x_photo', to='core.photo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='personxperson',
            constraint=models.UniqueConstraint(fields=('person_a', 'person_b'), name='unique_person_x_person'),
        ),
        migrations.AddConstraint(
            model_name='personxphoto',
            constraint=models.UniqueConstraint(fields=('person', 'photo'), name='unique_person_x_photo'),
        ),
    ]
