# Generated by Django 5.0 on 2023-12-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_author_authorxbook_authorxperson_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='motionpicture',
            constraint=models.UniqueConstraint(fields=('title', 'year_produced'), name='unique_motion_picture'),
        ),
    ]
