# Generated by Django 5.0 on 2023-12-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_personxperson_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personxperson',
            name='relationship',
            field=models.CharField(blank=True, choices=[('CHILD', 'Child'), ('DAUGHTER', 'Daughter'), ('FATHER', 'Father'), ('FRIEND', 'Friend'), ('GRANDCHILD', 'Grandchild'), ('GRANDDAUGHTER', 'Granddaughter'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('GRANDPARENT', 'Grandparent'), ('GRANDSON', 'Grandson'), ('HUSBAND', 'Husband'), ('MOTHER', 'Mother'), ('SIBLING', 'Sibling'), ('SON', 'Son'), ('SPOUSE', 'Spouse'), ('WIFE', 'Wife')], help_text='The relationship FROM person A TO person B', max_length=13),
        ),
    ]
