# Generated by Django 5.0 on 2023-12-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_personxperson_relationship'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personxperson',
            constraint=models.CheckConstraint(check=models.Q(('person_a', models.F('person_b')), _negated=True), name='person_x_person_not_self'),
        ),
    ]
