# Generated by Django 5.0 on 2023-12-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_personxperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonXPerson',
        ),
    ]
