# Generated by Django 5.0 on 2023-12-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_personxperson_person_x_person_not_self'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonXPerson',
        ),
    ]
