# Generated by Django 5.0 on 2024-01-09 09:19

import core.models.real_estate
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_beerxuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDiscreteManufactured',
            fields=[
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asset_discrete_manufactured', serialize=False, to='core.asset')),
                ('serial', models.CharField(help_text='Manufacturer serial number (or other unique identifier)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssetDiscreteRealEstate',
            fields=[
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('asset_discrete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asset_discrete_real_estate', serialize=False, to='core.assetdiscrete')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealEstateParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True)),
                ('has_residence', models.BooleanField(null=True)),
                ('lot_number', models.CharField(blank=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=3, help_text='Lot size, in acres', max_digits=8, null=True)),
                ('finished_area', core.models.real_estate.HouseAreaDecimalField(blank=True, decimal_places=2, help_text='Finished housing area, in square feet', max_digits=7, null=True)),
                ('unfinished_area', core.models.real_estate.HouseAreaDecimalField(blank=True, decimal_places=2, help_text='Area of unfinished spaces, in square feet', max_digits=7, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='assetdiscretexcatalogitem',
            name='asset_discrete',
        ),
        migrations.RemoveField(
            model_name='assetdiscretexcatalogitem',
            name='catalog_item',
        ),
        migrations.RemoveConstraint(
            model_name='catalogitemmanufactured',
            name='unique_catalog_item_manufactured',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='account_asset_real',
        ),
        migrations.AddField(
            model_name='accountassetreal',
            name='asset_discrete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_asset_real', to='core.assetdiscrete'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='asset',
            name='subtype',
            field=models.CharField(choices=[('DISCRETE', 'DISCRETE'), ('INVENTORY', 'INVENTORY')], max_length=9),
        ),
        migrations.AlterField(
            model_name='assetdiscrete',
            name='subtype',
            field=models.CharField(blank=True, choices=[('MANUFACTURED', 'MANUFACTURED'), ('REAL_ESTATE', 'REAL_ESTATE'), ('VEHICLE', 'VEHICLE')], max_length=12),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='subtype',
            field=models.CharField(blank=True, choices=[('DIGITAL_SONG', 'DIGITAL_SONG'), ('MANUFACTURED', 'MANUFACTURED'), ('MUSIC_ALBUM', 'MUSIC_ALBUM')], default='', max_length=31),
        ),
        migrations.AlterField(
            model_name='catalogitemmanufactured',
            name='part_number',
            field=models.CharField(blank=True, help_text='Model or Part Number', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='catalogitemmanufactured',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'part_number'), name='unique_catalog_item_manufactured', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='assetdiscretemanufactured',
            name='catalog_item_manufactured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_discrete_manufactured_set', related_query_name='asset_discrete_manufactured', to='core.catalogitemmanufactured'),
        ),
        migrations.AddField(
            model_name='assetdiscreterealestate',
            name='real_estate_parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asset_discrete_real_estate', to='core.realestateparcel'),
        ),
        migrations.DeleteModel(
            name='AssetDiscreteXCatalogItem',
        ),
        migrations.AddConstraint(
            model_name='assetdiscretemanufactured',
            constraint=models.UniqueConstraint(fields=('catalog_item_manufactured', 'serial'), name='unique_asset_discrete_manufactured_serial', nulls_distinct=False),
        ),
    ]
