# Generated by Django 5.0 on 2023-12-17 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_personxperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionPictureSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=63)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogItemMotionPictureRecording',
            fields=[
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_item_motion_picture_recording', serialize=False, to='core.catalogitem')),
                ('motion_picture_recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item_motion_picture_recording_set', related_query_name='catalog_item_motion_picture_recording', to='core.motionpicturerecording')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='motionpicture',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_picture_set', related_query_name='motion_picture', to='core.motionpictureseries'),
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_document_set', related_query_name='order_document', to='core.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
