# Generated by Django 5.0 on 2023-12-17 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_motionpictureseries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motionpictureseries',
            options={'verbose_name_plural': 'motion picture series'},
        ),
        migrations.AddField(
            model_name='motionpictureseries',
            name='parent_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_series', to='core.motionpictureseries'),
        ),
        migrations.AlterField(
            model_name='motionpictureseries',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=63, unique=True)),
                ('parent_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_series', to='core.bookseries')),
            ],
            options={
                'verbose_name_plural': 'book series',
            },
        ),
    ]
