# Generated by Django 5.0 on 2024-01-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_accountassetreal_asset_discrete_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountAssetRealXAssetDiscrete',
        ),
    ]
