# Generated by Django 5.0 on 2023-12-17 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_motionpictureseries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_set', related_query_name='book', to='core.bookseries'),
        ),
        migrations.CreateModel(
            name='CatalogItemBookPublication',
            fields=[
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='catalog_item_book_publication', serialize=False, to='core.catalogitem')),
                ('book_publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_item_book_publication_set', related_query_name='catalog_item_book_publication', to='core.bookpublication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
