# Generated by Django 5.0 on 2023-12-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_personxpersonrelation_personxpersonrelationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personxpersonrelationship',
            name='relationship',
            field=models.CharField(blank=True, choices=[('HUSBAND', 'Husband'), ('INSTRUCTOR', 'Instructor'), ('PARTNER', 'Partner'), ('SPOUSE', 'Spouse'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('WIFE', 'Wife')], help_text="The relationship FROM person A TO person B. Person A is Person B's ...", max_length=10),
        ),
    ]
