# Generated by Django 5.0 on 2023-12-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_personxpersonrelationship_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='preferred_name',
            field=models.CharField(max_length=255),
        ),
    ]
