# Generated by Django 5.0 on 2023-12-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_person_first_name_alter_person_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='music_albums',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicAlbumXPerson', to='core.musicalbum'),
        ),
        migrations.AlterField(
            model_name='musicalbum',
            name='personnel',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.MusicAlbumXPerson', to='core.person'),
        ),
    ]
