# Generated by Django 5.0 on 2023-12-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_musicalbumxvideogame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalbum',
            name='total_discs',
        ),
    ]
