# Generated by Django 5.0 on 2024-01-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_accountassetrealxassetdiscrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicartistxperson',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
