# Generated by Django 5.0 on 2023-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_musicalbum_total_discs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrecording',
            name='description',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
