# Generated by Django 5.0 on 2024-01-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_musicartistxperson_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeerXUser',
        ),
    ]
