# Generated by Django 5.0 on 2023-12-27 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_person_music_albums_alter_musicalbum_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='featured_photo',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('person_id', models.F('person_id')), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.personxphoto'),
        ),
        migrations.AddField(
            model_name='person',
            name='song_performances',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.PersonXSongPerformance', to='core.songperformance'),
        ),
    ]
