# Generated by Django 5.0 on 2023-12-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_person_featured_photo_person_song_performances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='featured_photo',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('person_id', models.F('person_id'))), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.personxphoto'),
        ),
    ]
