# Generated by Django 5.0 on 2023-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_songrecording_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='songrecording',
            constraint=models.UniqueConstraint(fields=('description', 'song'), name='unique_song_recording'),
        ),
    ]
