# Generated by Django 5.0 on 2023-12-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_songrecording_unique_song_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
