# Generated by Django 5.0 on 2023-12-27 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_person_featured_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='featured_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.personxphoto'),
        ),
    ]
