# Generated by Django 5.0 on 2023-12-19 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_song_is_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=63, unique=True)),
                ('section', models.CharField(blank=True, choices=[('B', 'Brass'), ('P', 'Percussion'), ('S', 'Strings'), ('W', 'Woodwind')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicalInstrumentXPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('musical_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musical_instrument_x_person_set', related_query_name='musical_instrument_x_person', to='core.musicalinstrument')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musical_instrument_x_person_set', related_query_name='musical_instrument_x_person', to='core.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='musicalinstrumentxperson',
            constraint=models.UniqueConstraint(fields=('musical_instrument', 'person'), name='unique_musical_instrument_x_person'),
        ),
    ]
