# Generated by Django 5.0 on 2023-12-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_musicalinstrument_musicalinstrumentxperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
