# Generated by Django 5.0 on 2023-12-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_photo_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='image_full',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='thumbnail',
            new_name='image_thumbnail',
        ),
    ]
