# Generated by Django 5.0 on 2023-12-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_image_photo_image_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_large',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_medium',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_small',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
    ]
