# Generated by Django 5.0 on 2023-12-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_person_nickname_person_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, max_length=31),
        ),
    ]
