# Generated by Django 5.0 on 2023-12-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_photo_image_large_photo_image_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songperformance',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='songarrangement',
            name='lyrics',
            field=models.TextField(blank=True, default=''),
        ),
    ]
