# Generated by Django 5.0 on 2023-12-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_person_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicartistxpersonactivity',
            name='date_active',
        ),
        migrations.RemoveField(
            model_name='musicartistxpersonactivity',
            name='date_inactive',
        ),
        migrations.AddField(
            model_name='musicartistxpersonactivity',
            name='year_active',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicartistxpersonactivity',
            name='year_inactive',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
