# Generated by Django 5.0 on 2023-12-20 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_musicartistxpersonactivity_date_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicartistxsongrecording',
            name='music_artist',
        ),
        migrations.RemoveField(
            model_name='musicartistxsongrecording',
            name='song_recording',
        ),
        migrations.RemoveField(
            model_name='songrecording',
            name='music_artists',
        ),
        migrations.RemoveField(
            model_name='songrecording',
            name='song',
        ),
        migrations.CreateModel(
            name='MusicArtistXSongPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('music_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_artist_x_song_performance_set', related_query_name='music_artist_x_song_performance', to='core.musicartist')),
            ],
        ),
        migrations.CreateModel(
            name='SongPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=63)),
                ('lyrics', models.TextField(blank=True, default='')),
                ('performance_type', models.CharField(choices=[('DEMO', 'Demo Recording'), ('LIVE', 'Live Performance'), ('STUDIO', 'Studio Recording')], default='STUDIO', max_length=6)),
                ('music_artists', models.ManyToManyField(related_name='+', through='core.MusicArtistXSongPerformance', to='core.musicartist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_performance_set', related_query_name='song_performance', to='core.song')),
            ],
        ),
        migrations.AddField(
            model_name='musicartistxsongperformance',
            name='song_performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_artist_x_song_performance_set', related_query_name='music_artist_x_song_performance', to='core.songperformance'),
        ),
        migrations.DeleteModel(
            name='MusicAlbumEditionXSongRecording',
        ),
        migrations.DeleteModel(
            name='MusicArtistXSongRecording',
        ),
        migrations.DeleteModel(
            name='SongRecording',
        ),
        migrations.AddConstraint(
            model_name='songperformance',
            constraint=models.UniqueConstraint(fields=('description', 'song'), name='unique_song_performance'),
        ),
        migrations.AddConstraint(
            model_name='musicartistxsongperformance',
            constraint=models.UniqueConstraint(fields=('music_artist', 'song_performance'), name='unique_music_artist_x_song_performance'),
        ),
    ]
