# Generated by Django 5.0 on 2023-12-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_songperformance_lyrics_songarrangement_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
