# Generated by Django 5.0 on 2023-12-20 04:03

import django.db.models.deletion
import django_base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_musicartistxsongrecording_music_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbumEditionXSongRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('disc_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('track_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('music_album_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_edition_x_song_recording_set', related_query_name='music_album_edition_x_song_recording', to='core.musicalbumedition')),
            ],
        ),
        migrations.CreateModel(
            name='SongRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(blank=True, null=True, validators=[django_base.validators.validate_positive_timedelta])),
                ('music_album_editions', models.ManyToManyField(related_name='+', through='core.MusicAlbumEditionXSongRecording', to='core.musicalbumedition')),
                ('song_performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='song_recording_set', related_query_name='song_recording', to='core.songperformance')),
            ],
        ),
        migrations.AddField(
            model_name='musicalbumeditionxsongrecording',
            name='song_recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_edition_x_song_recording_set', related_query_name='music_album_edition_x_song_recording', to='core.songrecording'),
        ),
        migrations.AddConstraint(
            model_name='songrecording',
            constraint=models.UniqueConstraint(fields=('duration', 'song_performance'), name='unique_song_recording'),
        ),
        migrations.AddConstraint(
            model_name='musicalbumeditionxsongrecording',
            constraint=models.UniqueConstraint(fields=('music_album_edition', 'song_recording'), name='unique_music_album_edition_x_song_recording'),
        ),
        migrations.AddConstraint(
            model_name='musicalbumeditionxsongrecording',
            constraint=models.UniqueConstraint(fields=('music_album_edition', 'disc_number', 'track_number'), name='unique_music_album_edition_x_song_recording_disc_track'),
        ),
    ]
