# Generated by Django 5.0 on 2023-12-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_musicalbum_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonXVideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_x_video_game_set', related_query_name='person_x_video_game', to='core.person')),
                ('video_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_x_video_game_set', related_query_name='person_x_video_game', to='core.videogame')),
            ],
        ),
        migrations.AddConstraint(
            model_name='personxvideogame',
            constraint=models.UniqueConstraint(fields=('person', 'video_game'), name='unique_person_x_video_game'),
        ),
    ]
