# Generated by Django 5.0 on 2023-12-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_personxvideogame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='personnel',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.PersonXVideoGame', to='core.person'),
        ),
    ]
