# Generated by Django 5.0 on 2023-12-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_musictag_musicartistxmusictag_musicalbumxmusictag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalbum',
            name='year_copyright',
        ),
        migrations.RemoveField(
            model_name='musicalbum',
            name='year_produced',
        ),
    ]
