# Generated by Django 5.0 on 2023-12-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_musicalbum_year_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicartistxpersonactivity',
            name='activity_type',
            field=models.CharField(choices=[('OFFICIAL', 'Official Member'), ('SESSION', 'Session Musician'), ('TOURING', 'Touring Member')], default='OFFICIAL', max_length=8),
        ),
    ]
