# Generated by Django 5.0 on 2023-12-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_musicartistxpersonactivity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicartistxpersonactivity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('OFFICIAL', 'Official Member'), ('SESSION', 'Session Musician'), ('TOURING', 'Touring Member')], max_length=8),
        ),
    ]
