# Generated by Django 5.0 on 2023-12-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_musicartistxpersonactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicartistxsongperformance',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
