# Generated by Django 5.0 on 2023-12-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_musicartistxsongperformance_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbumXPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('music_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_x_person_set', related_query_name='music_album_x_person', to='core.musicalbum')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_x_person_set', related_query_name='music_album_x_person', to='core.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='musicalbumxperson',
            constraint=models.UniqueConstraint(fields=('music_album', 'person'), name='unique_music_album_x_person'),
        ),
    ]
