# Generated by Django 5.0 on 2023-12-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_musicalbumxperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicartist',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
