# Generated by Django 5.0 on 2023-12-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_musicartist_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbumRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=31, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='musicalbum',
            name='personnel',
            field=models.ManyToManyField(blank=True, related_name='music_albums', through='core.MusicAlbumXPerson', to='core.person'),
        ),
        migrations.CreateModel(
            name='MusicAlbumXPersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('music_album_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_x_person_role_set', related_query_name='music_album_x_person_role', to='core.musicalbumrole')),
                ('music_album_x_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_x_person_role_set', related_query_name='music_album_x_person_role', to='core.musicalbumxperson')),
            ],
        ),
        migrations.AddConstraint(
            model_name='musicalbumxpersonrole',
            constraint=models.UniqueConstraint(fields=('music_album_role', 'music_album_x_person'), name='unique_music_album_x_person_role'),
        ),
    ]
