# Generated by Django 5.0 on 2023-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_musicalbumrole_musicalbum_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbumxperson',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
