# Generated by Django 5.0 on 2023-12-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_musicalbumxperson_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonXSongPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_x_song_performance_set', related_query_name='person_x_song_performance', to='core.person')),
                ('song_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_x_song_performance_set', related_query_name='person_x_song_performance', to='core.songperformance')),
            ],
        ),
        migrations.AddField(
            model_name='songperformance',
            name='personnel',
            field=models.ManyToManyField(related_name='+', through='core.PersonXSongPerformance', to='core.person'),
        ),
        migrations.AddConstraint(
            model_name='personxsongperformance',
            constraint=models.UniqueConstraint(fields=('person', 'song_performance'), name='unique_person_x_song_performance'),
        ),
    ]
