# Generated by Django 5.0 on 2023-12-20 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_songarrangement_remove_songperformance_music_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrecording',
            name='music_album_editions',
        ),
        migrations.AlterField(
            model_name='musicalbumeditionxsongrecording',
            name='song_recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_album_edition_x_song_recording_set', related_query_name='music_album_edition_x_song_recording', to='songrecording'),
        ),
        migrations.CreateModel(
            name='SongPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=63)),
                ('lyrics', models.TextField(blank=True, default='')),
                ('performance_type', models.CharField(choices=[('DEMO', 'Demo Recording'), ('LIVE', 'Live Performance'), ('STUDIO', 'Studio Recording')], default='STUDIO', max_length=6)),
                ('music_artists', models.ManyToManyField(related_name='+', through='core.MusicArtistXSongPerformance', to='core.musicartist')),
                ('personnel', models.ManyToManyField(related_name='+', through='core.PersonXSongPerformance', to='core.person')),
                ('song_arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_performance_set', related_query_name='song_performance', to='core.songarrangement')),
            ],
        ),
        migrations.AlterField(
            model_name='musicartistxsongperformance',
            name='song_performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_artist_x_song_performance_set', related_query_name='music_artist_x_song_performance', to='core.songperformance'),
        ),
        migrations.AlterField(
            model_name='personxsongperformance',
            name='song_performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_x_song_performance_set', related_query_name='person_x_song_performance', to='core.songperformance'),
        ),
        migrations.DeleteModel(
            name='SongRecording',
        ),
        migrations.AddConstraint(
            model_name='songperformance',
            constraint=models.UniqueConstraint(fields=('description', 'song_arrangement'), name='unique_song_performance'),
        ),
    ]
