# Generated by Django 5.0 on 2023-12-21 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_songarrangement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicArtistXSongArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_modified', models.DateTimeField(auto_now=True)),
                ('music_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_artist_x_song_arrangement_set', related_query_name='music_artist_x_song_arrangement', to='core.musicartist')),
                ('song_arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_artist_x_song_arrangement_set', related_query_name='music_artist_x_song_arrangement', to='core.songarrangement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='musicartistxsongarrangement',
            constraint=models.UniqueConstraint(fields=('music_artist', 'song_arrangement'), name='unique_music_artist_x_song_arrangement'),
        ),
    ]
