# Generated by Django 5.0 on 2023-12-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_musicartistxsongarrangement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_original',
        ),
    ]
