# Generated by Django 5.0 on 2023-12-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='key',
            new_name='option',
        ),
    ]
